In [1]:
n=[1,2,3,4,5,5,5,5,5]
print(n.count(5))

5


In [2]:
print(n.index(5))

4


In [3]:
n=[1,2,3,4]
n.insert(1,888)
print(n)

[1, 888, 2, 3, 4]


In [4]:
n=[1,2,3]
b=[4,5,6]
n.extend(b)
print(n)

[1, 2, 3, 4, 5, 6]


In [8]:
n=[1,2,3]
n.append(4)
print(n)

[1, 2, 3, 4]


In [9]:
n=[1,2,3,4]
n.remove(2)
print(n)

[1, 3, 4]


In [13]:
n=[1,2,3]
n.reverse()
print(n)

[3, 2, 1]


In [12]:
n=[1,2,3,4]
n.pop()
print(n)

[1, 2, 3]


In [14]:
n=["nivi","yammi","poo","nami"]
n.sort()
print(n)

['nami', 'nivi', 'poo', 'yammi']


In [16]:
n=["nivi","yammi","poo","nami"]
n.sort(reverse=True)
print(n)

['yammi', 'poo', 'nivi', 'nami']


In [17]:
x=[10,20,30,40]
y=x[:]
y[1]=777
print(x)
print(y)

[10, 20, 30, 40]
[10, 777, 30, 40]


In [18]:
x=[10,20,30,40]
y=x
y[1]=777
print(x)
print(y)

[10, 777, 30, 40]
[10, 777, 30, 40]


In [19]:
x=[10,20,30,40]
y=x.copy()
y[1]=777
print(x)
print(y)

[10, 20, 30, 40]
[10, 777, 30, 40]


In [20]:
a=[10,20,30]
b=[40,50,60]
c=a+b
print(c)

[10, 20, 30, 40, 50, 60]


In [21]:
x=[10,20,30]
y=x*3
print(y)

[10, 20, 30, 10, 20, 30, 10, 20, 30]


In [22]:
x=["MITE","MANGALORE","NITTE"]
y=["MITE","MANGALORE","NITTE"]
x==y
x!=y
z=["MITE","MANGALORE","NITTE"]
x==z

True

In [24]:
m=[10,20,30,[40,50,60]]



In [25]:
m[3]

[40, 50, 60]

In [27]:
m[3][1]

50

In [28]:
m.clear()

In [29]:
print(m)

[]


In [30]:
n=[1,2,3,4]
print(4 in n)

True


In [31]:
s=[2**x for x in range(1,6)]
print(s)

[2, 4, 8, 16, 32]


In [34]:
word=["mite","mysore","nivi"]
l=[w[0] for w in word]
print(l)

['m', 'm', 'n']


In [39]:
def times2(var):
    return var*2
seq=[1,2,3,4,5]
list(map(times2,seq))


[2, 4, 6, 8, 10]

In [40]:
seq=[1,2,3,4,5]
lambda var: var*2
list(map(lambda var: var*2,seq))
list(filter(lambda item:item%2==0,seq))

[2, 4]

In [35]:
def prime(n):
    flag=0
     for i in range(2,n):
            if n%i==0:
                 flag=1
                     if flag==1:
                            return 'Not a Prime'
                      else:
        return 'Prime'

        prime(4)

IndentationError: unexpected indent (<ipython-input-35-7f486ce04771>, line 3)

In [42]:
import numpy as np


In [43]:
my_list=[1,2,3,4]
my_list

[1, 2, 3, 4]

In [44]:
np.array(my_list)

array([1, 2, 3, 4])

In [45]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [46]:
np.array(my_matrix
    )

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [50]:
np.zeros(3)

array([0., 0., 0.])

In [51]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [52]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [60]:
np.ones(1,1)

TypeError: data type not understood

In [61]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [62]:
np.random.rand(5,5)

array([[0.26470368, 0.98494009, 0.73018005, 0.58132953, 0.7087739 ],
       [0.75910568, 0.8453778 , 0.95850398, 0.00878754, 0.85135472],
       [0.98273324, 0.68943804, 0.10493518, 0.21834576, 0.60787299],
       [0.94469869, 0.83649388, 0.64902179, 0.89425081, 0.4957684 ],
       [0.16676387, 0.4689341 , 0.13999164, 0.56102599, 0.43481247]])

In [63]:
np.random.randn(5,5)

array([[ 0.39454023,  0.19584707,  0.52445891, -1.91310857,  0.35230754],
       [-0.02342748,  0.88453557, -0.34287388, -0.67265449,  0.34420975],
       [ 0.84891741,  0.05076958,  0.85325739, -0.48235094,  1.47796608],
       [-0.42650671,  0.41798388, -1.52316406, -0.15070683,  0.75922666],
       [-0.22796905,  0.34851038, -0.52031444, -0.09850588, -1.04186807]])

In [66]:
np.random.randint(1,100,10)

array([ 8, 91, 39, 93, 23, 15, 70,  5, 81, 75])

In [67]:
arr=np.random.randint(1,100,10)
print(arr)

[27 96 38 80 68 16 24 89 98 31]


In [72]:
arr=np.arange(25)

In [74]:
runarr=np.random.randint(0,50,10)

In [75]:
print("hi")

hi


In [76]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [77]:
arr.max()

24

In [78]:
arr.argmax()

24

In [79]:
argmin and min

NameError: name 'argmin' is not defined

In [80]:
arr.shape

(25,)

In [81]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [82]:
arr.reshape(1,25).shape

(1, 25)

In [83]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [84]:
arr.reshape(25,1).shape

(25, 1)

In [85]:
arr.dtype

dtype('int32')

In [88]:
arr=np.arange(0,10)

In [89]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [90]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [91]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [92]:
arr/arr


C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [93]:
1/arr

C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [94]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [95]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [96]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [97]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [98]:
np.log(arr)

C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [99]:
arr=np.arange(0,11)

In [100]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [101]:
arr[8]

8

In [102]:
arr[1:5]

array([1, 2, 3, 4])

In [103]:
arr[0:5]=100

In [105]:
arr=np.arange(0,11)

In [106]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [107]:
arr>4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [108]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
arr=